//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RecruitmentSystem.Recruitment.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TalentAcquisitionEntities : DbContext
    {
        public TalentAcquisitionEntities()
            : base("name=TalentAcquisitionEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tbl_applicant> tbl_applicant { get; set; }
        public virtual DbSet<tbl_manpower_request> tbl_manpower_request { get; set; }
    }
}
