//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RecruitmentSystem.Recruitment.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_manpower_request
    {
        public int id { get; set; }
        public string mrfid { get; set; }
        public Nullable<System.DateTime> DateRequested { get; set; }
        public Nullable<System.DateTime> DateofDeployment { get; set; }
        public string RequiredPosition { get; set; }
        public Nullable<int> RequiredNumber { get; set; }
        public Nullable<int> cancel_number_requirement { get; set; }
        public string EducationalAttainment { get; set; }
        public string Course { get; set; }
        public string Gender { get; set; }
        public string AgeRequirement { get; set; }
        public string SkillType { get; set; }
        public string SpecificSkill { get; set; }
        public string Certification { get; set; }
        public string CostCenter { get; set; }
        public string Department { get; set; }
        public string JobDescription { get; set; }
        public string SalaryDetails { get; set; }
        public Nullable<decimal> BasicPay { get; set; }
        public Nullable<decimal> Cola { get; set; }
        public Nullable<decimal> Skilled { get; set; }
        public Nullable<decimal> Meal { get; set; }
        public Nullable<decimal> Transportation { get; set; }
        public Nullable<decimal> Gas { get; set; }
        public Nullable<decimal> Communication { get; set; }
        public Nullable<decimal> Motorcycle { get; set; }
        public Nullable<decimal> Clothing { get; set; }
        public Nullable<decimal> Medical { get; set; }
        public string PayoutDate { get; set; }
        public string WhotoLookfor { get; set; }
        public string Establishment { get; set; }
        public string OfficeAddresstoReport { get; set; }
        public string LocationofDeployment { get; set; }
        public string BusinessUnit { get; set; }
        public string Classification { get; set; }
        public string ProjectName { get; set; }
        public string CompanyRequested { get; set; }
        public string Requestor { get; set; }
        public string RequestorContactNumber { get; set; }
        public string RequestorEmailAddress { get; set; }
        public string coordinator_id { get; set; }
        public string am_1_id { get; set; }
        public string am_2_id { get; set; }
        public Nullable<bool> am_approved { get; set; }
        public Nullable<System.DateTime> am_date_approved { get; set; }
        public string recruitment_supervisor_id { get; set; }
        public Nullable<bool> recruitment_supervisor_approved { get; set; }
        public string oic_recruiter_id { get; set; }
        public Nullable<bool> oic_recruiter_approved { get; set; }
        public string recruiter_id { get; set; }
        public string status { get; set; }
        public string Remarks { get; set; }
        public Nullable<bool> am_rejected { get; set; }
        public Nullable<bool> cancel_mrf { get; set; }
        public Nullable<System.DateTime> date_completed { get; set; }
        public Nullable<System.DateTime> rs_approved_date { get; set; }
        public string EmploymentStatus { get; set; }
        public Nullable<System.DateTime> date_created { get; set; }
    }
}
